/** Generated by scripts/remap-hex-grid.mjs — do not edit by hand. */
export const MAP_VIEW_WIDTH = 821;
export const MAP_VIEW_HEIGHT = 399;
export const MAP_VIEWBOX_STR = "0 0 821 399";
export const MAP_FRAME_X = 29.2922;
export const MAP_FRAME_Y = -44.039;
